export const PersonReducer = {
  personDetails: [
    {
      id: "123qwe",
      name: "AMJAD",
      age: 34,
      discription: "he is a final year student  from mgm engineering collage",
      image: "redux3.png",
    },
    {
      id: "123qwe",
      name: "zubair",
      age: 34,
      discription: "he is a final year student from mgm engineering collage",
      image: "redux.png",
    },
    {
      id: "123qwe",
      name: "Aamer",
      age: 25,
      discription: "he is a second year student from mgm engineering collage",
      image: "redux2.png",
    },
    {
      id: "123qwe",
      name: "khawaja",
      age: 26,
      discription: "he is a third year student  from mgm engineering collage",
      image: "logo192.png",
    },
    {
      id: "123qwe",
      name: "salman",
      age: 27,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "umair",
      age: 30,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "rizwan",
      age: 25,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "zubair",
      age: 27,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "tausif",
      age: 27,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "sam",
      age: 20,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "mazhar",
      age: 25,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "aadil",
      age: 25,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "shoib",
      age: 22,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "rehan",
      age: 25,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
    {
      id: "123qwe",
      name: "rabey",
      age: 21,
      discription: "he is a first year student  from mgm engineering collage",
      image: "img.jpg",
    },
  ],
};
